apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: no-info
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: william_etotheipi
  flag: gaslightCTF{0b5cur1ty-41nt-n0t-s3curity}
  flagFormat: gaslightCTF{...}
  description: '<a href="https://en.wikipedia.org/wiki/Security_through_obscurity#Criticism">hint</a>

    '
  difficulty: easy
  categories:
    - crypto
  attachments:
    - fileName: output.txt
      downloadUrl: https://pantry.gaslightctf.cooking/0ay1adfjqpf6ckdygwg7mzyaa3sd27gd-no-info/output.txt
