apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: ucas
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: sportshead
  flag: gaslightCTF{m4n1f3st1ng_e4sy_0ff3r5_f0r_ev3ry0n3}
  flagFormat: gaslightCTF{...}
  description: 'these uni apps are getting harder and harder every year!

    '
  difficulty: easy
  categories:
    - pwn
  containers:
    - hostname: chall
      image: ghcr.io/gaslightctf/challs-2026/ucas:dev
      ports:
        - port: 1337
          protocol: tcp
          appProtocol: tcp
          type: publicTlsRoute
      dynamicFlag:
        content:
          path: /flag
  attachments:
    - fileName: ucas.tar.zst
      downloadUrl: https://pantry-dev.gaslightctf.cooking/2sc3rgd21xbsm9z707cqd8xz5c363qym-ucas/ucas.tar.zst
