apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: captive-portal
spec:
  displayName: Captive Portal
  author: Hollis_tang
  flag: gaslightCTF{sql-1nj3ction-b4e6acb1a1159a1f8d69d766999d3af5}
  flagFormat: gaslightCTF{...}
  description: 'Login and get the flag.

    '
  difficulty: easy
  categories:
    - web
  attachments: []
