apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: speedy
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: riyc
  flag: gaslightCTF{22.279,114.181}
  flagFormat: gaslightCTF{1.234,56.789}
  description: 'Flag format: <code>gaslightCTF{LAT,LONG}</code> (round to 3 d.p.)

    <br>

    tip: please try &pm;0.001 on your latitude! latitude was rounded down.

    '
  difficulty: easy
  categories:
    - misc
  attachments:
    - fileName: IMG_5441.png
      downloadUrl: https://pantry-dev.gaslightctf.cooking/bbnabp24b5sm2xxp8iadshn730kmv1bh-speedy/IMG_5441.png
