apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: where-the-dream-starts-1
spec:
  author: william_etotheipi
  flag: gaslightCTF{caesarreallylikedashiftofthree}
  flagFormat: gaslightCTF{...}
  displayName: Where the dream starts 1
  description: 'This one''s a classic. Can you understand the crypto from the maths?

    '
  difficulty: easy
  categories:
    - crypto
  attachments:
    - fileName: encrypt.py
      downloadUrl: https://pantry.gaslightctf.cooking/bq4jsmglavx4idqwa7a6qcmpmhiykwss-where-the-dream-starts-1/encrypt.py
    - fileName: output.txt
      downloadUrl: https://pantry.gaslightctf.cooking/bq4jsmglavx4idqwa7a6qcmpmhiykwss-where-the-dream-starts-1/output.txt
