apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: where-the-dream-starts-3
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: william_etotheipi
  flag: gaslightCTF{theindecipherablecipher}
  flagFormat: gaslightCTF{...}
  displayName: Where the dream starts 3
  description: 'Upon your successful attacks of the precedent ciphers, Vigenère invited
    you to his cipher workshop. Friedman and Kasiski are there too.

    <br><br>

    A modification of a very nice classic.

    '
  difficulty: medium
  categories:
    - crypto
  attachments:
    - fileName: encrypt.py
      downloadUrl: https://pantry-dev.gaslightctf.cooking/iq2a61hny6kckdnr3mj6g0x3hxhl2y0v-where-the-dream-starts-3/encrypt.py
    - fileName: output.txt
      downloadUrl: https://pantry-dev.gaslightctf.cooking/iq2a61hny6kckdnr3mj6g0x3hxhl2y0v-where-the-dream-starts-3/output.txt
