apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: where-the-dream-starts-3
spec:
  author: william_etotheipi
  flag: gaslightCTF{theindecipherablecipher}
  flagFormat: gaslightCTF{...}
  displayName: Where the dream starts 3
  description: 'Upon your successful attacks of the precedent ciphers, Vigenère invited
    you to his cipher workshop. Friedman and Kasiski are there too.

    <br><br>

    A very nice classic.

    '
  difficulty: medium
  categories:
    - crypto
  attachments:
    - fileName: output.txt
      downloadUrl: https://pantry-dev.gaslightctf.cooking/k22yrsd9cl653hapxvr18l6dx73svg12-where-the-dream-starts-3/output.txt
    - fileName: encrypt.py
      downloadUrl: https://pantry-dev.gaslightctf.cooking/k22yrsd9cl653hapxvr18l6dx73svg12-where-the-dream-starts-3/encrypt.py
