apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: badcat
spec:
  author: sportshead
  flag: gaslightCTF{f3l1n3_d3scr1pt0r_m30www}
  flagFormat: gaslightCTF{...}
  description: 'you''ve seen <a href="https://github.com/sharkdp/bat" target="_blank">batcat</a>,
    are you ready for badcat? <br>


    login with <code>badcat:b4788c115ea4eb42</code>

    '
  difficulty: easy
  categories:
    - pwn
  containers:
    - hostname: badcat
      image: ghcr.io/gaslightctf/challs-2026/badcat:dev
      ports:
        - port: 22
          protocol: tcp
          appProtocol: ssh
          type: publicTlsRoute
      dynamicFlag:
        content:
          path: /flag
          mode: 256
  attachments: []
