apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: 4-piece-puzzle
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: riyc
  flag: gaslightCTF{i_4m_f0ur_y3ars_01d}
  flagFormat: gaslightCTF{...}
  description: 'these <b>fou-fou-four</b> puzzle pieces are my favorite colours! excuse
    the stutter.

    '
  difficulty: medium
  categories:
    - forensics
  attachments:
    - fileName: puzzle_pieces.zip
      downloadUrl: https://pantry-dev.gaslightctf.cooking/p977fb71lkap4lk8q4nncfnlb133c4rj-4-piece-puzzle/puzzle_pieces.zip
