apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: The_ARPANET_era
spec:
  author: Hollis_tang
  flag: gaslightCTF{ftp_c0mm4nd_6ee3b619f2bae8d79f672365a21df52d}
  flagFormat: gaslightCTF{...}
  description: 'A good old FTP server.

    User: Rebecca

    Password: qwertyuiop

    '
  difficulty: easy
  categories:
    - misc
  tags:
    - ftp
    - networking
    - rfc959
  containers:
    - hostname: The_ARPANET_era
      image: ghcr.io/gaslightctf/challs-2026/the_arpanet_era:dev
      ports:
        - port: 2121
          protocol: tcp
          appProtocol: tcp
          type: publicTlsRoute
      dynamicFlag:
        env:
          name: FLAG
  attachments: []
