apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: the-arpanet-era
spec:
  author: Hollis_tang
  flag: gaslightCTF{ftp_c0mm4nd_6ee3b619f2bae8d79f672365a21df52d}
  flagFormat: gaslightCTF{...}
  displayName: The ARPANET era
  description: 'A good old FTP server. \


    User: `Rebecca` \

    Password: `qwertyuiop` \

    tip: use `socat TCP-LISTEN:2121,fork,reuseaddr SSL:host:31337` to forward the
    port locally

    '
  difficulty: easy
  categories:
    - misc
  tags:
    - ftp
    - networking
    - rfc959
  containers:
    - hostname: the-arpanet-era
      image: ghcr.io/gaslightctf/challs-2026/the_arpanet_era:dev
      ports:
        - port: 2121
          protocol: tcp
          appProtocol: tcp
          type: publicTlsRoute
      dynamicFlag:
        env:
          name: FLAG
  attachments: []
