apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: odyssey
spec:
  author: sportshead
  flag: gaslightCTF{37.974,23.724}
  flagFormat: gaslightCTF{1.234,56.789}
  description: 'Do I colour grade better than Christopher Nolan?

    <br>

    Flag format: <code>gaslightCTF{LAT,LONG}</code> (round to 3 d.p.)

    '
  difficulty: easy
  categories:
    - misc
  attachments:
    - fileName: 02.jpg
      downloadUrl: https://pantry.gaslightctf.cooking/qawmf78hk73b4nricaiqa8cc7172mbwv-odyssey/02.jpg
