apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: layered-pages
spec:
  hideUntil: '2026-08-16T00:00:00+00:00'
  author: riyc
  flag: gaslightCTF{c4rv3_1t_0ut}
  flagFormat: gaslightCTF{...}
  description: 'my desk is a mess! help me sort it out!

    '
  difficulty: easy
  categories:
    - forensics
  attachments:
    - fileName: gassy.zip
      downloadUrl: https://pantry-dev.gaslightctf.cooking/r99akm0x1i5513qmslf35jb7azcdgnkd-layered-pages/gassy.zip
