apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: tuning-keyboard-6
spec:
  displayName: Tuning Keyboard v6.7
  author: sportshead
  flag: gaslightCTF{p14n0_1n_r0bl0x_1s_h4rd}
  flagFormat: gaslightCTF{...}
  description: 'this song’s ending sounds a bit strange…

    <br><br>

    note: punctuation has been omitted. insert brackets and underscores as appropriate

    '
  difficulty: medium
  categories:
    - forensics
  attachments:
    - fileName: ttyut-iiiuy+12.wav
      downloadUrl: https://pantry-dev.gaslightctf.cooking/r9nmzky1jk432gl1hgpvwsnapfd96273-tuning-keyboard-6/ttyut-iiiuy+12.wav
