apiVersion: berg.norelect.ch/v1
kind: Challenge
metadata:
  namespace: berg
  name: messageboard
spec:
  author: sportshead
  flag: gaslightCTF{ar3_y0u_my_cl0s3_fr13nd_n0w?}
  flagFormat: gaslightCTF{...}
  description: 'I left a little message for only my closest friends :)

    '
  difficulty: easy
  categories:
    - web
  containers:
    - hostname: messageboard
      image: ghcr.io/gaslightctf/challs-2026/messageboard:dev
      ports:
        - port: 3000
          protocol: tcp
          appProtocol: http
          type: publicHttpRoute
      dynamicFlag:
        env:
          name: FLAG
    - hostname: db
      image: ghcr.io/gaslightctf/challs-2026/messageboard-db:dev
      ports:
        - port: 5432
          protocol: tcp
          appProtocol: postgresql
          type: internalPort
  attachments:
    - fileName: messageboard.tar.zst
      downloadUrl: https://pantry.gaslightctf.cooking/xhgrsfww21k4s26qgsf1xrgcdrh929ds-messageboard/messageboard.tar.zst
